<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Gibe.Umbraco.V13.Blog</PackageId>
		<PackageVersion>13.0.0</PackageVersion>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageTags>Gibe Umbraco Blog</PackageTags>
		<Authors>Gibe Digital Ltd</Authors>
		<Version>13.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>NET10,NET10</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="13.14.0" />
		<PackageReference Include="Gibe.Pager" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Gibe.Umbraco.Blog.Core\Gibe.Umbraco.Blog.Core.csproj" />
	</ItemGroup>
</Project>
